# Generated by Django 2.0.1 on 2019-03-02 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cart_id', models.CharField(blank=True, max_length=17)),
                ('total_mrp', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5)),
                ('total_selling_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Recently Updated')),
                ('payment_request', jsonfield.fields.JSONField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Address')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan', to='shop.Plan')),
                ('products', models.ManyToManyField(blank=True, related_name='products', to='shop.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='ProductOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suborder_id', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('SP', 'Order Shipped'), ('IP', 'In Process'), ('UO', 'Unverified Order'), ('PR', 'Pickup Requested'), ('CO', 'Order Completed'), ('OC', 'Order Confirmed'), ('RTOC', 'RTO Completed'), ('OD', 'Order Delivered'), ('RTO', 'RTO')], default='UO', max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=10, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('condition', models.CharField(blank=True, max_length=10, null=True)),
                ('mrp', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('discount', models.CharField(blank=True, max_length=10, null=True)),
                ('hunter_discount', models.CharField(blank=True, max_length=10, null=True)),
                ('total_discount', models.CharField(blank=True, max_length=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('delivery_charges', models.CharField(blank=True, max_length=10, null=True)),
                ('final_selling_price', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Address')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'verbose_name_plural': 'Product Orders',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suborder_id', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('payment_method', models.CharField(blank=True, max_length=10, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_amount', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('security_deposit', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('subscription_duration', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('extra_month', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('available_swaps', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Address')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subscription Orders',
            },
        ),
    ]
