# Generated by Django 2.0.1 on 2019-01-08 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Address'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='total_mrp',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='total_selling_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
