# Generated by Django 2.0.1 on 2019-01-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20190108_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcart',
            name='address',
        ),
        migrations.AlterField(
            model_name='productcart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.Product'),
        ),
    ]
