# Generated by Django 2.0.1 on 2019-03-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20190227_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('RTOC', 'RTO Completed'), ('UO', 'Unverified Order'), ('IP', 'In Process'), ('SP', 'Order Shipped'), ('RTO', 'RTO'), ('OC', 'Order Confirmed'), ('PR', 'Pickup Requested'), ('OD', 'Order Delivered'), ('CO', 'Order Completed')], default='UO', max_length=20, null=True),
        ),
    ]
