# Generated by Django 2.0.1 on 2019-03-12 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20190303_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='carts.Cart'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('RTO', 'RTO'), ('PR', 'Pickup Requested'), ('OD', 'Order Delivered'), ('OC', 'Order Confirmed'), ('UO', 'Unverified Order'), ('SP', 'Order Shipped'), ('RTOC', 'RTO Completed'), ('IP', 'In Process'), ('CO', 'Order Completed')], default='UO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='suborder_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionorders',
            name='suborder_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
