# Generated by Django 2.0.1 on 2019-01-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20190108_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
