# Generated by Django 2.0.1 on 2019-01-20 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20190120_2328'),
        ('carts', '0004_productcart_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Address'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Recently Updated'),
        ),
    ]
