# Generated by Django 2.0.1 on 2019-01-23 13:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20190120_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='payments',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
