# Generated by Django 2.0.1 on 2019-03-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20190315_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorders',
            old_name='discount',
            new_name='shipping_link',
        ),
        migrations.RenameField(
            model_name='productorders',
            old_name='type',
            new_name='tracking_id',
        ),
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('CO', 'Order Completed'), ('OC', 'Order Confirmed'), ('PR', 'Pickup Requested'), ('OD', 'Order Delivered'), ('SP', 'Order Shipped'), ('RTO', 'RTO'), ('UO', 'Unverified Order'), ('RTOC', 'RTO Completed'), ('IP', 'In Process')], default='UO', max_length=20, null=True),
        ),
    ]
