# Generated by Django 2.0.1 on 2019-01-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_productcart_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcart',
            old_name='payments',
            new_name='payment_request',
        ),
    ]
