# Generated by Django 2.0.1 on 2019-01-23 18:09

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20190123_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='payment_captured',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
