# Generated by Django 2.0.1 on 2019-03-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20190325_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('CO', 'Order Completed'), ('UO', 'Unverified Order'), ('RTO', 'RTO'), ('SP', 'Order Shipped'), ('IP', 'In Process'), ('OC', 'Order Confirmed'), ('PR', 'Pickup Requested'), ('RTOC', 'RTO Completed'), ('OD', 'Order Delivered')], default='UO', max_length=20, null=True),
        ),
    ]
