# Generated by Django 2.0.1 on 2019-01-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_productcart_payment_captured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcart',
            name='payment_captured',
        ),
        migrations.AddField(
            model_name='productcart',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productcart',
            name='payment_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
