# Generated by Django 2.0.1 on 2019-01-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20190124_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suborder_id', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('OC', 'Order Confirmed'), ('UO', 'Unverified Order'), ('CO', 'Order Completed'), ('IP', 'In Process'), ('PR', 'Pickup Requested'), ('OD', 'Order Delivered'), ('SP', 'Order Shipped')], max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=10, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('condition', models.CharField(blank=True, max_length=10, null=True)),
                ('mrp', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('discount', models.CharField(blank=True, max_length=10, null=True)),
                ('hunter_discount', models.CharField(blank=True, max_length=10, null=True)),
                ('total_discount', models.CharField(blank=True, max_length=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('delivery_charges', models.CharField(blank=True, max_length=10, null=True)),
                ('final_selling_price', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_provider', models.CharField(blank=True, max_length=20, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
