# Generated by Django 2.0.1 on 2019-03-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20190330_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('RTOC', 'RTO Completed'), ('CO', 'Order Completed'), ('OD', 'Order Delivered'), ('SP', 'Order Shipped'), ('OC', 'Order Confirmed'), ('IP', 'In Process'), ('PR', 'Pickup Requested'), ('RTO', 'RTO'), ('UO', 'Unverified Order')], default='UO', max_length=20, null=True),
        ),
    ]
