# Generated by Django 2.0.1 on 2019-03-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_auto_20190331_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('UO', 'Unverified Order'), ('PR', 'Pickup Requested'), ('RTOC', 'RTO Completed'), ('OD', 'Order Delivered'), ('RTO', 'RTO'), ('CO', 'Order Completed'), ('OC', 'Order Confirmed'), ('SP', 'Order Shipped'), ('IP', 'In Process')], default='UO', max_length=20, null=True),
        ),
    ]
