# Generated by Django 2.0.1 on 2019-01-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_orders_ordertracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('OC', 'Order Confirmed'), ('RTO', 'RTO'), ('OD', 'Order Delivered'), ('RTOC', 'RTO Completed'), ('SP', 'Order Shipped'), ('PR', 'Pickup Requested'), ('UO', 'Unverified Order'), ('IP', 'In Process'), ('CO', 'Order Completed')], max_length=20, null=True),
        ),
    ]
