# Generated by Django 2.0.1 on 2019-04-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20190401_1549'),
        ('carts', '0011_auto_20190331_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pay_game_products',
            field=models.ManyToManyField(blank=True, related_name='pay_game_products', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('RTO', 'RTO'), ('OD', 'Order Delivered'), ('RTOC', 'RTO Completed'), ('PR', 'Pickup Requested'), ('CO', 'Order Completed'), ('IP', 'In Process'), ('UO', 'Unverified Order'), ('OC', 'Order Confirmed'), ('SP', 'Order Shipped')], default='UO', max_length=20, null=True),
        ),
    ]
