# Generated by Django 2.0.1 on 2019-01-29 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_auto_20190129_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('IP', 'In Process'), ('SP', 'Order Shipped'), ('CO', 'Order Completed'), ('RTO', 'RTO'), ('UO', 'Unverified Order'), ('RTOC', 'RTO Completed'), ('OD', 'Order Delivered'), ('OC', 'Order Confirmed'), ('PR', 'Pickup Requested')], max_length=20, null=True),
        ),
    ]
