# Generated by Django 2.0.1 on 2019-01-31 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_auto_20190129_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suborder_id', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('SP', 'Order Shipped'), ('OD', 'Order Delivered'), ('UO', 'Unverified Order'), ('RTOC', 'RTO Completed'), ('PR', 'Pickup Requested'), ('IP', 'In Process'), ('RTO', 'RTO'), ('OC', 'Order Confirmed'), ('CO', 'Order Completed')], default='UO', max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=10, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.TextField(blank=True, max_length=400, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('condition', models.CharField(blank=True, max_length=10, null=True)),
                ('mrp', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('discount', models.CharField(blank=True, max_length=10, null=True)),
                ('hunter_discount', models.CharField(blank=True, max_length=10, null=True)),
                ('total_discount', models.CharField(blank=True, max_length=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('delivery_charges', models.CharField(blank=True, max_length=10, null=True)),
                ('final_selling_price', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Product Orders',
            },
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.ProductOrders'),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
