# Generated by Django 2.0.1 on 2019-04-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_auto_20190401_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('SP', 'Order Shipped'), ('IP', 'In Process'), ('OD', 'Order Delivered'), ('PR', 'Pickup Requested'), ('RTO', 'RTO'), ('UO', 'Unverified Order'), ('RTOC', 'RTO Completed'), ('OC', 'Order Confirmed'), ('CO', 'Order Completed')], default='UO', max_length=20, null=True),
        ),
    ]
