# Generated by Django 2.0.1 on 2019-01-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20190131_1928'),
        ('carts', '0013_auto_20190131_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan', to='shop.Plan'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('SP', 'Order Shipped'), ('RTO', 'RTO'), ('IP', 'In Process'), ('RTOC', 'RTO Completed'), ('UO', 'Unverified Order'), ('PR', 'Pickup Requested'), ('OC', 'Order Confirmed'), ('OD', 'Order Delivered'), ('CO', 'Order Completed')], default='UO', max_length=20, null=True),
        ),
    ]
