# Generated by Django 2.0.1 on 2019-06-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_auto_20190409_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('CO', 'Order Completed'), ('RTO', 'RTO'), ('OC', 'Order Confirmed'), ('SP', 'Order Shipped'), ('UO', 'Unverified Order'), ('OD', 'Order Delivered'), ('IP', 'In Process'), ('PR', 'Pickup Requested'), ('RTOC', 'RTO Completed')], default='UO', max_length=20, null=True),
        ),
    ]
