# Generated by Django 2.0.1 on 2019-06-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_auto_20190625_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('IP', 'In Process'), ('SP', 'Order Shipped'), ('RTO', 'RTO'), ('RTOC', 'RTO Completed'), ('UO', 'Unverified Order'), ('CO', 'Order Completed'), ('PR', 'Pickup Requested'), ('OD', 'Order Delivered'), ('OC', 'Order Confirmed')], default='UO', max_length=20, null=True),
        ),
    ]
