# Generated by Django 2.0.1 on 2019-02-01 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0040_auto_20190201_1816'),
        ('carts', '0014_auto_20190131_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseModel')),
                ('cart_id', models.CharField(blank=True, max_length=17)),
                ('total_mrp', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5)),
                ('total_selling_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Recently Updated')),
                ('payment_request', jsonfield.fields.JSONField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Address')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan', to='shop.Plan')),
                ('products', models.ManyToManyField(blank=True, related_name='products', to='shop.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Cart',
            },
            bases=('shop.basemodel',),
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='address',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='user',
        ),
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('PR', 'Pickup Requested'), ('OD', 'Order Delivered'), ('RTO', 'RTO'), ('SP', 'Order Shipped'), ('IP', 'In Process'), ('CO', 'Order Completed'), ('UO', 'Unverified Order'), ('RTOC', 'RTO Completed'), ('OC', 'Order Confirmed')], default='UO', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ProductCart',
        ),
    ]
