# Generated by Django 2.0.1 on 2019-02-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_auto_20190201_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suborder_id', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('IP', 'In Process'), ('UO', 'Unverified Order'), ('OC', 'Order Confirmed'), ('CO', 'Order Completed')], default='UO', max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=10, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_amount', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('security_deposit', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('subscription_duration', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('extra_month', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('available_swaps', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordertracking',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('UO', 'Unverified Order'), ('OC', 'Order Confirmed'), ('RTO', 'RTO'), ('OD', 'Order Delivered'), ('RTOC', 'RTO Completed'), ('PR', 'Pickup Requested'), ('IP', 'In Process'), ('SP', 'Order Shipped'), ('CO', 'Order Completed')], default='UO', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='OrderTracking',
        ),
    ]
