# Generated by Django 2.0.1 on 2019-07-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_auto_20190626_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('CO', 'Order Completed'), ('UO', 'Unverified Order'), ('OC', 'Order Confirmed'), ('RTO', 'RTO'), ('SP', 'Order Shipped'), ('PR', 'Pickup Requested'), ('RTOC', 'RTO Completed'), ('IP', 'In Process'), ('OD', 'Order Delivered')], default='UO', max_length=20, null=True),
        ),
    ]
