# Generated by Django 2.0.1 on 2019-02-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0016_auto_20190201_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionorders',
            options={'verbose_name_plural': 'Subscription Orders'},
        ),
        migrations.RemoveField(
            model_name='subscriptionorders',
            name='status',
        ),
        migrations.AddField(
            model_name='subscriptionorders',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionorders',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('SP', 'Order Shipped'), ('PR', 'Pickup Requested'), ('OD', 'Order Delivered'), ('UO', 'Unverified Order'), ('IP', 'In Process'), ('RTOC', 'RTO Completed'), ('CO', 'Order Completed'), ('RTO', 'RTO'), ('OC', 'Order Confirmed')], default='UO', max_length=20, null=True),
        ),
    ]
