# Generated by Django 2.0.1 on 2019-07-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0016_auto_20190704_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('RTOC', 'RTO Completed'), ('OC', 'Order Confirmed'), ('UO', 'Unverified Order'), ('RTO', 'RTO'), ('CO', 'Order Completed'), ('PR', 'Pickup Requested'), ('IP', 'In Process'), ('SP', 'Order Shipped'), ('OD', 'Order Delivered')], default='UO', max_length=20, null=True),
        ),
    ]
