# Generated by Django 2.0.1 on 2019-07-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0017_auto_20190704_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('OC', 'Order Confirmed'), ('RTO', 'RTO'), ('IP', 'In Process'), ('OD', 'Order Delivered'), ('SP', 'Order Shipped'), ('UO', 'Unverified Order'), ('PR', 'Pickup Requested'), ('CO', 'Order Completed'), ('RTOC', 'RTO Completed')], default='UO', max_length=20, null=True),
        ),
    ]
