# Generated by Django 2.0.1 on 2019-02-01 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0017_auto_20190201_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionorders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('UO', 'Unverified Order'), ('RTO', 'RTO'), ('IP', 'In Process'), ('RTOC', 'RTO Completed'), ('PR', 'Pickup Requested'), ('CO', 'Order Completed'), ('OD', 'Order Delivered'), ('OC', 'Order Confirmed'), ('SP', 'Order Shipped')], default='UO', max_length=20, null=True),
        ),
    ]
