# Generated by Django 2.0.1 on 2019-07-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0018_auto_20190704_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('PR', 'Pickup Requested'), ('UO', 'Unverified Order'), ('CO', 'Order Completed'), ('SP', 'Order Shipped'), ('RTO', 'RTO'), ('OC', 'Order Confirmed'), ('IP', 'In Process'), ('RTOC', 'RTO Completed'), ('OD', 'Order Delivered')], default='UO', max_length=20, null=True),
        ),
    ]
