# Generated by Django 2.0.1 on 2019-02-04 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0018_auto_20190201_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('UO', 'Unverified Order'), ('OC', 'Order Confirmed'), ('PR', 'Pickup Requested'), ('IP', 'In Process'), ('OD', 'Order Delivered'), ('RTOC', 'RTO Completed'), ('RTO', 'RTO'), ('SP', 'Order Shipped'), ('CO', 'Order Completed')], default='UO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionorders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
