# Generated by Django 2.0.1 on 2019-02-05 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_auto_20190205_1311'),
        ('carts', '0020_auto_20190205_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorders',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Address'),
        ),
        migrations.AddField(
            model_name='subscriptionorders',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Address'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('CO', 'Order Completed'), ('OD', 'Order Delivered'), ('OC', 'Order Confirmed'), ('SP', 'Order Shipped'), ('UO', 'Unverified Order'), ('RTO', 'RTO'), ('RTOC', 'RTO Completed'), ('IP', 'In Process'), ('PR', 'Pickup Requested')], default='UO', max_length=20, null=True),
        ),
    ]
