# Generated by Django 2.0.1 on 2019-02-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0022_auto_20190209_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='status',
            field=models.CharField(blank=True, choices=[('SP', 'Order Shipped'), ('PR', 'Pickup Requested'), ('RTO', 'RTO'), ('IP', 'In Process'), ('CO', 'Order Completed'), ('RTOC', 'RTO Completed'), ('OD', 'Order Delivered'), ('OC', 'Order Confirmed'), ('UO', 'Unverified Order')], default='UO', max_length=20, null=True),
        ),
    ]
