# Generated by Django 2.0.1 on 2019-02-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('news', 'News'), ('deals', 'Deals'), ('blog', 'Blog')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('banner_left', 'Banner Left'), ('coverpage_top', 'Coverpage Top'), ('coverpage_bottom', 'Coverpage Bottom'), ('banner_right', 'Banner Right'), ('coverpage_center', 'Coverpage Center')], default='coverpage_top', max_length=100),
        ),
    ]
