# Generated by Django 2.0.1 on 2018-12-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_attribute',
            old_name='product',
            new_name='blog',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('deals', 'Deals'), ('blog', 'Blog'), ('news', 'News')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('half-yearly', 'Half Yearly'), ('quaterly', 'Quaterly')], default='Monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('U', 'Used'), ('N', 'New')], default='new', max_length=10),
        ),
    ]
