# Generated by Django 2.0.1 on 2018-12-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181207_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='categories',
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quaterly', 'Quaterly'), ('half-yearly', 'Half Yearly'), ('yearly', 'Yearly')], default='Monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_status',
            field=models.CharField(choices=[('I', 'In Stock'), ('O', 'Out of Stock')], default='Inactive', max_length=20),
        ),
    ]
