# Generated by Django 2.0.1 on 2019-03-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190227_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('views', models.CharField(max_length=60, verbose_name='View')),
                ('exceptionclass', models.CharField(max_length=120, verbose_name='Exception Class')),
                ('message', models.TextField(max_length=1000, verbose_name='Exception Message')),
            ],
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('coverpage_top', 'Coverpage Top'), ('banner_left', 'Banner Left'), ('coverpage_bottom', 'Coverpage Bottom'), ('coverpage_center', 'Coverpage Center'), ('banner_right', 'Banner Right')], default='coverpage_top', max_length=100),
        ),
    ]
