# Generated by Django 2.0.1 on 2018-12-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181207_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('deals', 'Deals'), ('news', 'News'), ('blog', 'Blog')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[(1, 'Monthly'), (3, 'Quaterly'), (12, 'Yearly'), (6, 'Half Yearly')], default='Monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used')], default='new', max_length=10),
        ),
    ]
