# Generated by Django 2.0.1 on 2019-03-12 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190303_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('deals', 'Deals'), ('news', 'News'), ('blog', 'Blog')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_status',
            field=models.CharField(choices=[('O', 'Out of Stock'), ('I', 'In Stock'), ('S', 'Subscription Only')], default='O', max_length=20),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productattribute', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('banner_left', 'Banner Left'), ('coverpage_center', 'Coverpage Center'), ('banner_right', 'Banner Right'), ('coverpage_top', 'Coverpage Top'), ('coverpage_bottom', 'Coverpage Bottom')], default='coverpage_top', max_length=100),
        ),
    ]
