# Generated by Django 2.0.1 on 2018-12-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181207_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='slug',
            field=models.SlugField(default='', max_length=120, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('deals', 'Deals'), ('blog', 'Blog'), ('news', 'News')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('12', 'Yearly'), ('3', 'Quaterly'), ('1', 'Monthly'), ('6', 'Half Yearly')], default='Monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('U', 'Used'), ('N', 'New')], default='new', max_length=10),
        ),
    ]
