# Generated by Django 2.0.1 on 2018-12-07 17:11

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181207_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, validators=[shop.models.min_value_validator]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('news', 'News'), ('deals', 'Deals')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('6', 'Half Yearly'), ('3', 'Quaterly'), ('1', 'Monthly'), ('12', 'Yearly')], default='Monthly', max_length=20),
        ),
    ]
