# Generated by Django 2.0.1 on 2019-03-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190325_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='refundable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='type',
            field=models.CharField(blank=True, choices=[('GB', 'Game Based'), ('SB', 'Subscription Based')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(db_index=True, help_text='Title Name of Blog/Article', max_length=150),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='swaps',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Available Swaps'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_status',
            field=models.CharField(choices=[('S', 'Subscription Only'), ('O', 'Out of Stock'), ('I', 'In Stock')], default='O', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='launch_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('coverpage_bottom', 'Coverpage Bottom'), ('banner_left', 'Banner Left'), ('banner_right', 'Banner Right'), ('coverpage_top', 'Coverpage Top'), ('coverpage_center', 'Coverpage Center')], default='coverpage_top', max_length=100),
        ),
    ]
