# Generated by Django 2.0.1 on 2018-12-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20181207_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='plan_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('news', 'News'), ('blog', 'Blog'), ('deals', 'Deals')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('3', 'Quaterly'), ('12', 'Yearly'), ('1', 'Monthly'), ('6', 'Half Yearly')], default='Monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used')], default='new', max_length=10),
        ),
    ]
