# Generated by Django 2.0.1 on 2019-03-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190329_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('deals', 'Deals'), ('news', 'News'), ('blog', 'Blog')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('SB', 'Subscription Based'), ('GB', 'Game Based')], default='SB', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('coverpage_center', 'Coverpage Center'), ('banner_left', 'Banner Left'), ('coverpage_top', 'Coverpage Top'), ('banner_right', 'Banner Right'), ('coverpage_bottom', 'Coverpage Bottom')], default='coverpage_top', max_length=100),
        ),
    ]
