# Generated by Django 2.0.1 on 2018-12-12 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20181208_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo_Cards',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseModel')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('type', models.CharField(choices=[('coverpage_top', 'Coverpage_Top'), ('coverpage_bottom', 'Coverpage Bottom'), ('coverpage_center', 'Coverpage Center'), ('banner_left', 'Banner Left'), ('banner_right', 'Banner Right')], default='Coverpage Top', max_length=100)),
                ('active', models.BooleanField()),
                ('link', models.CharField(max_length=200, null=True)),
            ],
            bases=('shop.basemodel',),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('deals', 'Deals'), ('blog', 'Blog'), ('news', 'News')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('3', 'Quaterly'), ('1', 'Monthly'), ('6', 'Half Yearly'), ('12', 'Yearly')], default='Monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_status',
            field=models.CharField(choices=[('O', 'Out of Stock'), ('I', 'In Stock')], default='O', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='promo_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Promo_Cards'),
        ),
    ]
