# Generated by Django 2.0.1 on 2018-12-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20181212_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCard',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseModel')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('type', models.CharField(choices=[('banner_left', 'Banner Left'), ('banner_right', 'Banner Right'), ('coverpage_center', 'Coverpage Center'), ('coverpage_top', 'Coverpage_Top'), ('coverpage_bottom', 'Coverpage Bottom')], default='Coverpage Top', max_length=100)),
                ('active', models.BooleanField()),
                ('link', models.CharField(max_length=200, null=True)),
            ],
            bases=('shop.basemodel',),
        ),
        migrations.RemoveField(
            model_name='promo_cards',
            name='basemodel_ptr',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('deals', 'Deals'), ('news', 'News')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='photo',
            name='promo_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.PromoCard'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('6', 'Half Yearly'), ('3', 'Quaterly'), ('1', 'Monthly'), ('12', 'Yearly')], default='Monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('U', 'Used'), ('N', 'New')], default='new', max_length=10),
        ),
        migrations.DeleteModel(
            name='Promo_Cards',
        ),
    ]
