# Generated by Django 2.0.1 on 2019-03-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190331_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocard',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('news', 'News'), ('deals', 'Deals')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('U', 'Used')], default='N', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_status',
            field=models.CharField(choices=[('S', 'Subscription Only'), ('I', 'In Stock'), ('O', 'Out of Stock')], default='O', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('coverpage_bottom', 'Coverpage Bottom'), ('coverpage_center', 'Coverpage Center'), ('banner_left', 'Banner Left'), ('coverpage_top', 'Coverpage Top'), ('banner_right', 'Banner Right')], default='coverpage_top', max_length=100),
        ),
    ]
