# Generated by Django 2.0.1 on 2019-04-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190331_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('deals', 'Deals'), ('news', 'News')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('GB', 'Game Based'), ('SB', 'Subscription Based')], default='SB', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_status',
            field=models.CharField(choices=[('S', 'Subscription Only'), ('O', 'Out of Stock'), ('I', 'In Stock')], default='O', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='plan',
            field=models.ManyToManyField(blank=True, related_name='plans', to='shop.Plan'),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('banner_left', 'Banner Left'), ('coverpage_bottom', 'Coverpage Bottom'), ('banner_right', 'Banner Right'), ('coverpage_top', 'Coverpage Top'), ('coverpage_center', 'Coverpage Center')], default='coverpage_top', max_length=100),
        ),
    ]
