# Generated by Django 2.0.1 on 2019-06-25 16:44

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20190409_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellYourGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(blank=True, max_length=150, null=True)),
                ('game_category', models.CharField(choices=[('ps4', 'Playstation 4'), ('xbox_one', 'Xbox One')], max_length=30)),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='category',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='category',
            name='path',
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(default=3, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=4, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('news', 'News'), ('deals', 'Deals')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('P', 'Published'), ('U', 'Unpublished')], default='U', max_length=15),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_description_meta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='csvimporter',
            name='path',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Game Hunter\\gamehunter\\media'), upload_to='csv_file_uploads', validators=[shop.models.validate_csv_file]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('GB', 'Game Based'), ('SB', 'Subscription Based')], default='SB', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_status',
            field=models.CharField(choices=[('I', 'In Stock'), ('O', 'Out of Stock'), ('S', 'Subscription Only')], default='O', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('coverpage_center', 'Coverpage Center'), ('coverpage_top', 'Coverpage Top'), ('banner_right', 'Banner Right'), ('coverpage_bottom', 'Coverpage Bottom'), ('banner_left', 'Banner Left')], default='coverpage_top', max_length=100),
        ),
    ]
