# Generated by Django 2.0.1 on 2018-12-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20181220_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='blog_attribute',
            options={'verbose_name_plural': 'Blog Attribute'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('news', 'News'), ('blog', 'Blog'), ('deals', 'Deals')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('12', 'Yearly'), ('1', 'Monthly'), ('3', 'Quaterly'), ('6', 'Half Yearly')], default='Monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('coverpage_center', 'Coverpage Center'), ('banner_right', 'Banner Right'), ('banner_left', 'Banner Left'), ('coverpage_top', 'Coverpage Top'), ('coverpage_bottom', 'Coverpage Bottom')], default='Coverpage Top', max_length=100),
        ),
    ]
