# Generated by Django 2.0.1 on 2019-06-26 08:46

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20190625_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={},
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='attribute',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='path',
        ),
        migrations.AddField(
            model_name='attribute',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.Attribute'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='rght',
            field=models.PositiveIntegerField(default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=3, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('deals', 'Deals'), ('news', 'News'), ('blog', 'Blog')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('SB', 'Subscription Based'), ('GB', 'Game Based')], default='SB', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_status',
            field=models.CharField(choices=[('I', 'In Stock'), ('S', 'Subscription Only'), ('O', 'Out of Stock')], default='O', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('coverpage_top', 'Coverpage Top'), ('coverpage_center', 'Coverpage Center'), ('banner_right', 'Banner Right'), ('coverpage_bottom', 'Coverpage Bottom'), ('banner_left', 'Banner Left')], default='coverpage_top', max_length=100),
        ),
    ]
