# Generated by Django 2.0.1 on 2018-12-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20181221_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='monthly_swaps',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('news', 'News'), ('deals', 'Deals')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('banner_left', 'Banner Left'), ('coverpage_center', 'Coverpage Center'), ('coverpage_top', 'Coverpage Top'), ('banner_right', 'Banner Right'), ('coverpage_bottom', 'Coverpage Bottom')], default='Coverpage Top', max_length=100),
        ),
    ]
