# Generated by Django 2.0.1 on 2019-07-27 05:34

import django.core.files.storage
from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20190704_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocard',
            name='type',
        ),
        migrations.AddField(
            model_name='promocard',
            name='promocard_clickable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promocard',
            name='promocard_type',
            field=models.CharField(choices=[('banner_right', 'Banner Right'), ('coverpage_bottom', 'Coverpage Bottom'), ('coverpage_top', 'Coverpage Top'), ('coverpage_center', 'Coverpage Center'), ('banner_left', 'Banner Left')], default='coverpage_top', max_length=100),
        ),
        migrations.AlterField(
            model_name='csvimporter',
            name='path',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Game Hunter\\gamehunter\\media'), upload_to='csv_file_uploads', validators=[shop.models.validate_csv_file]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('SB', 'Subscription Based'), ('GB', 'Game Based')], default='SB', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_status',
            field=models.CharField(choices=[('S', 'Subscription Only'), ('O', 'Out of Stock'), ('I', 'In Stock')], default='O', max_length=20),
        ),
    ]
