# Generated by Django 2.0.1 on 2018-12-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20181221_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='monthly_swaps',
        ),
        migrations.AddField(
            model_name='plan',
            name='swaps',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total Swaps'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('deals', 'Deals'), ('blog', 'Blog'), ('news', 'News')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_status',
            field=models.CharField(choices=[('I', 'In Stock'), ('O', 'Out of Stock')], default='O', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('banner_left', 'Banner Left'), ('coverpage_bottom', 'Coverpage Bottom'), ('coverpage_top', 'Coverpage Top'), ('coverpage_center', 'Coverpage Center'), ('banner_right', 'Banner Right')], default='Coverpage Top', max_length=100),
        ),
    ]
