# Generated by Django 2.0.1 on 2018-12-25 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20181225_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='developer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_developer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Brand'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('deals', 'Deals'), ('news', 'News')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_developer',
            field=models.BooleanField(default=True, verbose_name='Developer'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_manufacturer',
            field=models.BooleanField(default=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_publisher',
            field=models.BooleanField(default=True, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('banner_left', 'Banner Left'), ('coverpage_top', 'Coverpage Top'), ('coverpage_center', 'Coverpage Center'), ('coverpage_bottom', 'Coverpage Bottom'), ('banner_right', 'Banner Right')], default='coverpage_top', max_length=100),
        ),
    ]
