# Generated by Django 2.0.1 on 2018-12-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20181225_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_manufacturer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='shop.Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_publisher': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='shop.Brand'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('news', 'News'), ('deals', 'Deals')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='developer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_developer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer', to='shop.Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_status',
            field=models.CharField(choices=[('O', 'Out of Stock'), ('I', 'In Stock')], default='O', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('coverpage_bottom', 'Coverpage Bottom'), ('banner_left', 'Banner Left'), ('coverpage_top', 'Coverpage Top'), ('banner_right', 'Banner Right'), ('coverpage_center', 'Coverpage Center')], default='coverpage_top', max_length=100),
        ),
    ]
