# Generated by Django 2.0.1 on 2019-01-02 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0022_auto_20181225_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImporter',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseModel')),
                ('data_type', models.CharField(choices=[('PD', 'Product')], max_length=10, verbose_name='Data Type')),
                ('path', models.FileField(upload_to='media/test')),
            ],
            options={
                'verbose_name_plural': 'CSV Importer',
            },
            bases=('shop.basemodel',),
        ),
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseModel')),
                ('cart_id', models.CharField(max_length=10)),
                ('total_mrp', models.IntegerField()),
                ('total_selling_price', models.IntegerField()),
                ('total_discount', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Address')),
            ],
            bases=('shop.basemodel',),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='item_status',
            field=models.CharField(choices=[('O', 'Out of Stock'), ('I', 'In Stock')], default='O', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='plan',
            field=models.ManyToManyField(related_name='products', to='shop.Plan'),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('coverpage_bottom', 'Coverpage Bottom'), ('coverpage_top', 'Coverpage Top'), ('banner_left', 'Banner Left'), ('coverpage_center', 'Coverpage Center'), ('banner_right', 'Banner Right')], default='coverpage_top', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcart',
            name='products',
            field=models.ManyToManyField(related_name='products', to='shop.Product'),
        ),
        migrations.AddField(
            model_name='productcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
