# Generated by Django 2.0.1 on 2019-01-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20190102_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcart',
            name='address',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='user',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('news', 'News'), ('deals', 'Deals')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='plan',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.Plan'),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('banner_right', 'Banner Right'), ('banner_left', 'Banner Left'), ('coverpage_center', 'Coverpage Center'), ('coverpage_top', 'Coverpage Top'), ('coverpage_bottom', 'Coverpage Bottom')], default='coverpage_top', max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductCart',
        ),
    ]
