# Generated by Django 2.0.1 on 2019-01-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20190123_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('news', 'News'), ('blog', 'Blog'), ('deals', 'Deals')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('U', 'Used'), ('N', 'New')], default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_status',
            field=models.CharField(choices=[('O', 'Out of Stock'), ('I', 'In Stock')], default='O', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('banner_right', 'Banner Right'), ('coverpage_top', 'Coverpage Top'), ('coverpage_center', 'Coverpage Center'), ('coverpage_bottom', 'Coverpage Bottom'), ('banner_left', 'Banner Left')], default='coverpage_top', max_length=100),
        ),
    ]
