# Generated by Django 2.0.1 on 2019-01-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20190124_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('deals', 'Deals'), ('blog', 'Blog'), ('news', 'News')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used')], default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('coverpage_top', 'Coverpage Top'), ('coverpage_center', 'Coverpage Center'), ('coverpage_bottom', 'Coverpage Bottom'), ('banner_right', 'Banner Right'), ('banner_left', 'Banner Left')], default='coverpage_top', max_length=100),
        ),
    ]
