# Generated by Django 2.0.1 on 2019-02-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20190131_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('news', 'News'), ('deals', 'Deals'), ('blog', 'Blog')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used')], default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='type',
            field=models.CharField(choices=[('coverpage_top', 'Coverpage Top'), ('coverpage_center', 'Coverpage Center'), ('banner_right', 'Banner Right'), ('banner_left', 'Banner Left'), ('coverpage_bottom', 'Coverpage Bottom')], default='coverpage_top', max_length=100),
        ),
    ]
